// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591

namespace Storage.Db.Cluster
{
	[Table("bucket", Schema = "public")]
	public partial class Bucket
	{
		[Column("bucket_id"  , DataType  = DataType.Int32   , DbType   = "integer"    , IsPrimaryKey = true  , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      BucketId   { get; set; } // integer
		[Column("bucket_name", CanBeNull = false            , DataType = DataType.Text, DbType       = "text"                                                             )] public string   BucketName { get; set; } // text
		[Column("node_id"    , DataType  = DataType.Int32   , DbType   = "integer"                                                                                        )] public int      NodeId     { get; set; } // integer
		[Column("ttl"        , DataType  = DataType.Interval, DbType   = "interval"                                                                                       )] public TimeSpan Ttl        { get; set; } // interval

		#region Associations
		/// <summary>
		/// bucket_node_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(NodeId), OtherKey = nameof(Cluster.Node.NodeId))]
		public Node Node { get; set; }
		#endregion
	}
}
