// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591

namespace Storage.Db.Cluster
{
	public partial class ClusterConnection : DataConnection
	{
		public ClusterConnection()
		{
			InitDataContext();
		}

		public ClusterConnection(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public ClusterConnection(DataOptions<ClusterConnection> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Bucket> Buckets => this.GetTable<Bucket>();
		public ITable<File>   Files   => this.GetTable<File>();
		public ITable<Node>   Nodes   => this.GetTable<Node>();
	}
}
