// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;

#pragma warning disable 1573, 1591

namespace Storage.Db.Cluster
{
	[Table("file", Schema = "public")]
	public partial class File
	{
		[Column("file_id"  , DataType  = DataType.Int64, DbType   = "bigint"     , IsPrimaryKey = true  , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   FileId   { get; set; } // bigint
		[Column("file_name", CanBeNull = false         , DataType = DataType.Text, DbType       = "text"                                                             )] public string FileName { get; set; } // text
		[Column("bucket_id", DataType  = DataType.Int32, DbType   = "integer"                                                                                        )] public int    BucketId { get; set; } // integer
		[Column("node_id"  , DataType  = DataType.Int32, DbType   = "integer"                                                                                        )] public int    NodeId   { get; set; } // integer

		#region Associations
		/// <summary>
		/// file_node_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(NodeId), OtherKey = nameof(Cluster.Node.NodeId))]
		public Node Node { get; set; }
		#endregion
	}
}
