<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Evolve" Version="3.2.0"/>
        <PackageReference Include="linq2db" Version="6.3.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.18" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.18" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.18" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
        <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    </ItemGroup>

</Project>
