// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Storage.Client
{
    /// <summary>Storage.Api</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface IStorageApi
    {
        /// <summary>Список корзин в кластере.</summary>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Get("/bucket")]
        Task<ICollection<BucketDto>> GetBucketsAsync(CancellationToken cancellationToken = default);

        /// <summary>Создание новой корзины.</summary>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/bucket")]
        Task<BucketDto> CreateBucketAsync([Body] BucketCreateDto body, CancellationToken cancellationToken = default);

        /// <summary>Запрос корзины по её ИД.</summary>
        /// <param name="bucketId">ИД корзины.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Get("/bucket/{bucketId}")]
        Task<BucketDto> GetBucketAsync(string bucketId, CancellationToken cancellationToken = default);

        /// <summary>Изменение параметров корзины.</summary>
        /// <param name="bucketId">Идентификатор корзины.</param>
        /// <param name="body">Новые параметры корзины.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/bucket/{bucketId}")]
        Task<BucketDto> UpdateBucketAsync(string bucketId, [Body] BucketPatchDto body, CancellationToken cancellationToken = default);

        /// <summary>Загрузка файла в хранилище.</summary>
        /// <param name="bucketId">bucketId parameter</param>
        /// <param name="formFile">formFile parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Multipart]
        [Headers("Accept: application/json")]
        [Post("/file/{bucketId}")]
        Task<string> UploadFileAsync(string bucketId, StreamPart formFile, CancellationToken cancellationToken = default);

        /// <summary>Скачивание файла из хранилища.</summary>
        /// <param name="fileKey">Ключ файла.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>OK</description>
        /// </item>
        /// </list>
        /// </returns>
        [Get("/file/{fileKey}")]
        Task<ApiResponse<Stream>> DownloadFileAsync(string fileKey, CancellationToken cancellationToken = default);

        /// <summary>Список узлов в кластере.</summary>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Get("/node")]
        Task<ICollection<NodeDto>> GetNodesAsync(CancellationToken cancellationToken = default);

    }


}