<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\MinimalApi.Hosting.Abstractions\MinimalApi.Hosting.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    </ItemGroup>

</Project>
