// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591

namespace Storage.Cluster.DataAccess.Model
{
	[Table("node", Schema = "public")]
	public partial class Node
	{
		[Column("node_name", CanBeNull = false         , DataType = DataType.NVarChar, DbType     = "character varying(16)", IsPrimaryKey = true                     )] public string NodeName { get; set; } // character varying(16)
		[Column("host_name", CanBeNull = false         , DataType = DataType.Text    , DbType     = "text"                                                           )] public string HostName { get; set; } // text
		[Column("node_id"  , DataType  = DataType.Int16, DbType   = "smallint"       , IsIdentity = true                   , SkipOnInsert = true, SkipOnUpdate = true)] public short  NodeId   { get; set; } // smallint

		#region Associations
		/// <summary>
		/// bucket_node_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(NodeName), OtherKey = nameof(Bucket.NodeId))]
		public IEnumerable<Bucket> Buckets { get; set; }

		/// <summary>
		/// file_node_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(NodeName), OtherKey = nameof(File.NodeId))]
		public IEnumerable<File> Files { get; set; }
		#endregion
	}
}
