// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591

namespace Storage.Cluster.DataAccess.Model
{
	[Table("node", Schema = "public")]
	public partial class Node
	{
		[Column("node_id"  , CanBeNull = false, DataType = DataType.NVarChar, DbType = "character varying(16)", IsPrimaryKey = true)] public string NodeId   { get; set; } // character varying(16)
		[Column("host_name", CanBeNull = false, DataType = DataType.Text    , DbType = "text"                                      )] public string HostName { get; set; } // text

		#region Associations
		/// <summary>
		/// bucket_node_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(NodeId), OtherKey = nameof(Bucket.NodeId))]
		public IEnumerable<Bucket> Buckets { get; set; }

		/// <summary>
		/// file_node_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(NodeId), OtherKey = nameof(File.NodeId))]
		public IEnumerable<File> Files { get; set; }
		#endregion
	}
}
