// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591

namespace Storage.Cluster.Model
{
	[Table("bucket", Schema = "public")]
	public partial class Bucket
	{
		[Column("bucket_id", CanBeNull = false            , DataType = DataType.NVarChar, DbType = "character varying(16)", IsPrimaryKey = true)] public string   BucketId { get; set; } // character varying(16)
		[Column("node_id"  , CanBeNull = false            , DataType = DataType.NVarChar, DbType = "character varying(16)"                     )] public string   NodeId   { get; set; } // character varying(16)
		[Column("ttl"      , DataType  = DataType.Interval, DbType   = "interval"                                                              )] public TimeSpan Ttl      { get; set; } // interval

		#region Associations
		/// <summary>
		/// bucket_node_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(NodeId), OtherKey = nameof(Model.Node.NodeId))]
		public Node Node { get; set; }
		#endregion
	}
}
