// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591

namespace Storage.Db.Node
{
	[Table("file", Schema = "public")]
	public partial class File
	{
		[Column("file_id"    , DataType  = DataType.Int64         , DbType   = "bigint"                      , IsPrimaryKey = true  , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long           FileId     { get; set; } // bigint
		[Column("file_name"  , CanBeNull = false                  , DataType = DataType.Text                 , DbType       = "text"                                                             )] public string         FileName   { get; set; } // text
		[Column("package_id" , DataType  = DataType.Int64         , DbType   = "bigint"                                                                                                          )] public long           PackageId  { get; set; } // bigint
		[Column("file_size"  , DataType  = DataType.Int64         , DbType   = "bigint"                                                                                                          )] public long           FileSize   { get; set; } // bigint
		[Column("file_offset", DataType  = DataType.Int64         , DbType   = "bigint"                                                                                                          )] public long           FileOffset { get; set; } // bigint
		[Column("created_at" , DataType  = DataType.DateTimeOffset, DbType   = "timestamp (6) with time zone"                                                                                    )] public DateTimeOffset CreatedAt  { get; set; } // timestamp (6) with time zone

		#region Associations
		/// <summary>
		/// file_package_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(PackageId), OtherKey = nameof(Db.Node.Package.PackageId))]
		public Package Package { get; set; }
		#endregion
	}
}
