// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591

namespace Storage.Db.Node
{
	public partial class NodeConnection : DataConnection
	{
		public NodeConnection()
		{
			InitDataContext();
		}

		public NodeConnection(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public NodeConnection(DataOptions<NodeConnection> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<File>    Files    => this.GetTable<File>();
		public ITable<Package> Packages => this.GetTable<Package>();
	}
}
