// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591

namespace Storage.Db.Node
{
	[Table("node", Schema = "public")]
	public partial class Node
	{
		[Column("node_guid", DataType = DataType.Guid, DbType = "uuid", IsPrimaryKey = true)] public Guid NodeGuid { get; set; } // uuid
	}
}
