// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591

namespace Storage.Db.Node
{
	[Table("package", Schema = "public")]
	public partial class Package
	{
		[Column("package_id"  , DataType  = DataType.Int64  , DbType   = "bigint"         , IsPrimaryKey = true                   , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   PackageId   { get; set; } // bigint
		[Column("file_path"   , CanBeNull = false           , DataType = DataType.Text    , DbType       = "text"                                                                              )] public string FilePath    { get; set; } // text
		[Column("bucket_id"   , CanBeNull = false           , DataType = DataType.NVarChar, DbType       = "character varying(16)"                                                             )] public string BucketId    { get; set; } // character varying(16)
		[Column("size"        , DataType  = DataType.Int64  , DbType   = "bigint"                                                                                                              )] public long   Size        { get; set; } // bigint
		[Column("write_offset", DataType  = DataType.Int64  , DbType   = "bigint"                                                                                                              )] public long   WriteOffset { get; set; } // bigint
		[Column("is_closed"   , DataType  = DataType.Boolean, DbType   = "boolean"                                                                                                             )] public bool   IsClosed    { get; set; } // boolean

		#region Associations
		/// <summary>
		/// file_package_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(PackageId), OtherKey = nameof(File.PackageId))]
		public IEnumerable<File> Files { get; set; }
		#endregion
	}
}
